# Generated by Django 5.0.7 on 2024-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=15)),
                ('permanent_address', models.CharField(max_length=255)),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('previous_school', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('degree_name', models.CharField(max_length=255)),
                ('previous_training', models.TextField(blank=True, null=True)),
                ('theatre_experience', models.TextField(blank=True, null=True)),
                ('performance_experience', models.TextField(blank=True, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('acting_group', models.TextField(blank=True, null=True)),
                ('desired_course', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('drama_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('terms_agreed', models.BooleanField(default=False)),
            ],
        ),
    ]
