# Generated by Django 5.0.7 on 2024-10-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='admissionform',
            name='terms_agreed',
        ),
        migrations.AddField(
            model_name='admissionform',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='degree_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='desired_course',
            field=models.CharField(default='Default Course', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='drama_certificate',
            field=models.FileField(default=2, upload_to='certificates/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='previous_school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='temporary_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
