# Generated by Django 5.0.7 on 2024-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
