# Generated by Django 5.0.7 on 2024-09-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0003_coursedescription_courseduration_coursefees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
