# Generated by Django 5.0.7 on 2024-09-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0004_delete_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('time_slots', models.TextField()),
                ('batches', models.TextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dance.course')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dance.course')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='dance.course')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseDescription',
        ),
        migrations.DeleteModel(
            name='CourseDuration',
        ),
        migrations.DeleteModel(
            name='CourseFees',
        ),
        migrations.DeleteModel(
            name='CourseSyllabus',
        ),
    ]
