# Generated by Django 5.0.7 on 2024-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0005_course_duration_fee_syllabus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
