# Generated by Django 5.0.7 on 2024-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0008_slideritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('register_button_text', models.CharField(default='Register Now', max_length=50)),
                ('register_button_link', models.URLField(default='#')),
                ('view_button_text', models.CharField(default='View More', max_length=50)),
                ('view_button_link', models.URLField(default='#')),
            ],
        ),
        migrations.DeleteModel(
            name='SliderItem',
        ),
    ]
