# Generated by Django 5.0.7 on 2024-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0009_cardslideritem_delete_slideritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslideritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
    ]
