# Generated by Django 5.0.7 on 2024-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0010_alter_cardslideritem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='text',
            field=models.TextField(default=True, null=True),
        ),
    ]
