# Generated by Django 5.0.7 on 2024-09-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0011_fee_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='text2',
            field=models.TextField(default=True, null=True),
        ),
    ]
