# Generated by Django 5.0.7 on 2024-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0012_fee_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslideritem',
            name='subtitle',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='cardslideritem',
            name='title',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
