# Generated by Django 5.0.7 on 2024-09-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setCardSliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('register_button_text', models.CharField(default='Register Now', max_length=50)),
                ('register_button_link', models.URLField(default='#')),
                ('view_button_text', models.CharField(default='View More', max_length=50)),
                ('view_button_link', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='setcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='setCoursesyllbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='setFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='setSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='setCourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='set.setcoursesyllbi')),
            ],
        ),
        migrations.CreateModel(
            name='setDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('time_slots', models.TextField()),
                ('batches', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='set.setcourse')),
            ],
        ),
        migrations.CreateModel(
            name='setFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('text', models.TextField(default=True, null=True)),
                ('text2', models.TextField(default=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='set.setcourse')),
            ],
        ),
    ]
