# Generated by Django 5.0.7 on 2024-09-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=100)),
                ('tutor_image', models.ImageField(upload_to='tutors/')),
                ('course_title', models.CharField(max_length=200)),
                ('course_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_count', models.IntegerField()),
                ('registration_link', models.URLField()),
            ],
        ),
    ]
