# Generated by Django 5.0.7 on 2024-09-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashcourse',
            name='video_count',
        ),
    ]
