# Generated by Django 5.0.7 on 2024-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_dashcourse_video_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashcourse',
            name='tutor_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
