# Generated by Django 5.0.7 on 2024-08-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_alter_sliderimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderImage',
            new_name='SlidersImage',
        ),
    ]
