# Generated by Django 5.0.7 on 2024-08-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_rename_sliderimage_slidersimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderssOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='course/image')),
                ('text', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SliderssTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='course/image')),
                ('text', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
    ]
