# Generated by Django 5.0.7 on 2024-08-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0003_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='description',
            new_name='descrip',
        ),
        migrations.RenameField(
            model_name='play',
            old_name='title',
            new_name='heading',
        ),
    ]
