# Generated by Django 5.0.7 on 2024-08-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0007_sliderone_slidertwo_delete_aboutusinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderone',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='sliderone',
            old_name='alt_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='slidertwo',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='slidertwo',
            old_name='alt_text',
            new_name='text',
        ),
    ]
