# Generated by Django 5.0.7 on 2024-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0008_rename_image_sliderone_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderone',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slidertwo',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
