# Generated by Django 5.0.7 on 2024-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0010_teammember_alter_sliderone_desc_alter_slidertwo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='posters/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
