# Generated by Django 5.0.7 on 2024-08-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0012_imagecontent_textcontent_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course/image')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageContent',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
