# Generated by Django 5.0.7 on 2024-08-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0013_poster_delete_imagecontent_delete_textcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='image',
            new_name='ima',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='name',
            new_name='intro',
        ),
    ]
