# Generated by Django 5.0.7 on 2024-08-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0014_rename_image_poster_ima_rename_name_poster_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='position_class',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
