# Generated by Django 5.0.7 on 2024-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0015_poster_position_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=20)),
                ('speed', models.CharField(choices=[('slower', 'Slower'), ('lower50', 'Lower50')], max_length=20)),
                ('size', models.CharField(choices=[('bottom', 'Bottom'), ('top', 'Top')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
