# Generated by Django 5.0.7 on 2024-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0016_feature_photo_delete_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image_url', models.URLField()),
                ('order_index', models.IntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(),
        ),
    ]
