# Generated by Django 5.0.7 on 2024-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0018_alter_coursecontent_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(default='#')),
            ],
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='course/image'),
        ),
    ]
