# Generated by Django 5.0.7 on 2024-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0019_featurecard_alter_coursecontent_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading_part1', models.CharField(max_length=255)),
                ('subheading_part2', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, default=True)),
                ('image', models.ImageField(blank=True, default=True, upload_to='course/image')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
