# Generated by Django 5.0.7 on 2024-08-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0020_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='subheading_part3',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subheading_part1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subheading_part2',
            field=models.CharField(max_length=500),
        ),
    ]
