# Generated by Django 5.0.7 on 2024-08-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0022_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='image_url',
        ),
    ]
