# Generated by Django 5.0.7 on 2024-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0023_remove_workshop_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image_url',
            field=models.URLField(blank=True, default=True),
        ),
    ]
