# Generated by Django 5.0.7 on 2024-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0025_workshopnew_delete_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
