# Generated by Django 5.0.7 on 2024-08-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0026_dropdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dropdown',
            new_name='AddCourse',
        ),
    ]
