# Generated by Django 5.0.7 on 2024-08-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0028_addcourseabout_adddropdowncourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='button_url',
            field=models.URLField(blank=True, default=False, max_length=250),
        ),
    ]
