# Generated by Django 5.0.7 on 2024-08-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0029_play_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='btn_text',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
