# Generated by Django 5.0.7 on 2024-08-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0032_servicecard_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourseabout',
        ),
    ]
