# Generated by Django 5.0.7 on 2024-08-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0034_delete_sliderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderOne',
        ),
        migrations.DeleteModel(
            name='SliderTwo',
        ),
    ]
