# Generated by Django 5.0.7 on 2024-08-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0035_delete_sliderone_delete_slidertwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
