# Generated by Django 5.0.7 on 2024-09-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0036_delete_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddDropdownCourses',
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.DeleteModel(
            name='FeatureCard',
        ),
        migrations.DeleteModel(
            name='Workshopnew',
        ),
    ]
