# Generated by Django 5.0.7 on 2024-09-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0037_delete_adddropdowncourses_delete_coursecontent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicecard',
        ),
    ]
