# Generated by Django 5.0.7 on 2024-10-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0038_delete_servicecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
