# Generated by Django 5.0.7 on 2024-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actingcardslideritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='acting_images/'),
        ),
    ]
