# Generated by Django 5.0.7 on 2024-09-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acting', '0002_alter_actingcardslideritem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actingcardslideritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actingimages/'),
        ),
    ]
