# Generated by Django 5.0.7 on 2024-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
