# Generated by Django 5.0.7 on 2024-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDropdownCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True, default=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='course/image')),
                ('order_index', models.IntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Workshopnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='workshops/')),
                ('thumbnail1', models.ImageField(upload_to='workshops/')),
                ('thumbnail2', models.ImageField(upload_to='workshops/')),
                ('thumbnail3', models.ImageField(upload_to='workshops/')),
                ('facebook_icon', models.URLField()),
                ('instagram_icon', models.URLField()),
                ('twitter_icon', models.URLField()),
            ],
        ),
    ]
